### ISSUE TITLE
☔ [JS] LlamaIndex.TS instrumentation

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/openinference#173]
Add [LlamaIndex.TS](https://github.com/run-llama/LlamaIndexTS) instrumentation

## Spike
- [x] [JS][LlamaIndex][spike] use callbacks to create spans and see if they stack with OpenAI spans
- [ ] [JS][LlamaIndex][spike] investigate LlamaIndex stream primitives and see if they have controllers and tries
- [ ] [JS][LlamaIndex] Spans for top level span types
  - [ ] #615
  - [x] #616
  - [x] #617
  - [ ] [JS][LlamaIndex] support reranker span kind
  - [ ] [JS][LlamaIndex] support agent span kind
  - [ ] #618
- [ ] [JS][LlamaIndex] support streaming responses
- [x] #613
- [x] #614
- [ ] [JS][LlamaIndex] bump to the latest version of llamaindex and pin in instrumentation
- [ ] [JS][LlamaIndex] add more unit tests

## Setup
- [x] #195

## Open Questions
- Should we use the callback system? Does it provide enough visibility to map to OpenInference
- How do we handle async generators?

**Comment by mikeldking** [comment]
@dosu-bot you provided python for js! That's not helpful
