### ISSUE TITLE
🗺 GuardrailsAI instrumentation

### ISSUE THREAD

**Issue by harrisonchu** [Arize-ai/openinference#564]
Instrumentation for [GuardrailsAI](https://www.guardrailsai.com/)

- [ ] create a tutorial for guardrails
- [ ] add documentation on arize-phoenix
- [ ] document integration on guadrrails https://github.com/guardrails-ai/guardrails
- [ ] document integration on opentelemetry.io

**Comment by harrisonchu** [comment]
this has been completed
