### ISSUE TITLE
🗺️  OpenInference Core - TypeScript

### ISSUE THREAD

**Issue by mikeldking** [Arize-ai/openinference#650]
As an instrumentor of a js app, I'd like a common set of utilities and configuration afordances to let me customize my spans using openinference semantics.

## Infra
- [x] scaffold the project
- [ ] [js][openinference-core] re-export opentelemetry supress tracing

## Config
- [ ] [js][openinference-core] scaffold openinference TraceConfig and environment variables

## Inheritable attributes

As app builder, I may want to set attributes that can be inherited by all child spans so I can add openinference attributes to child spans (inherit)

Example using a callback
```typescript
import { usingPromptTemplate, getContextAttributes } from "@arizeai/openinference-core"
import { context } from "@opentelemetry/api"

const TPL = "hello {name}";

function task() => {
     // Right here there are no inheritable attributes on the context
     context.with(usingPromptTemplate({ promptTemplate: TPL}, context.getActive()), (activeContext) => {
          // Inheritable attributes set here
          const attrs = getContextAttributes(activeContext);
          llm.invoke();
     });
     // context attributes restored here with no user changes needed
}

```
- [x] [js][openinference-core] inheritable attributes support
- [x] #654
- [x] #655
- [x] #764
- [x] [js][openinference-core]  inheritable tag attributes support
- [x] #776

## Documentation

**Comment by mikeldking** [comment]
Marking as completed by @Parker-Stafford
